// Generated by Bisonc++ V4.05.00 on Thu, 05 Jun 2014 10:35:51 -0700

// $insert class.ih
#include "parser_impl.hpp"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them

// $insert debugincludes
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <iomanip>

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {271, 1}, // 1: program ->  func_def_list
     {272, 0}, // 2: func_def_list ->  <empty>
     {272, 1}, // 3: func_def_list ->  func_def
     {272, 3}, // 4: func_def_list (';') ->  func_def ';' func_def_list
     {273, 4}, // 5: func_def (ID) ->  ID func_param_spec '=' func_body
     {274, 0}, // 6: func_param_spec ->  <empty>
     {274, 3}, // 7: func_param_spec ('(') ->  '(' func_param_list ')'
     {276, 1}, // 8: func_param_list (ID) ->  ID
     {276, 3}, // 9: func_param_list (ID) ->  ID ',' func_param_list
     {275, 1}, // 10: func_body ->  expr
     {277, 3}, // 11: expr (EQ) ->  expr EQ expr
     {277, 3}, // 12: expr (NEQ) ->  expr NEQ expr
     {277, 3}, // 13: expr (LESS) ->  expr LESS expr
     {277, 3}, // 14: expr (MORE) ->  expr MORE expr
     {277, 3}, // 15: expr ('+') ->  expr '+' expr
     {277, 3}, // 16: expr ('-') ->  expr '-' expr
     {277, 3}, // 17: expr ('*') ->  expr '*' expr
     {277, 3}, // 18: expr ('/') ->  expr '/' expr
     {277, 3}, // 19: expr ('(') ->  '(' expr ')'
     {277, 1}, // 20: expr ->  range
     {277, 1}, // 21: expr ->  for
     {277, 1}, // 22: expr ->  call
     {277, 1}, // 23: expr ->  literal
     {281, 1}, // 24: literal (INT) ->  INT
     {281, 1}, // 25: literal (REAL) ->  REAL
     {278, 3}, // 26: range (DOTDOT) ->  expr DOTDOT expr
     {278, 2}, // 27: range (DOTDOT) ->  expr DOTDOT
     {278, 2}, // 28: range (DOTDOT) ->  DOTDOT expr
     {280, 3}, // 29: call (ID) ->  ID call_args call_range
     {282, 0}, // 30: call_args ->  <empty>
     {282, 3}, // 31: call_args ('(') ->  '(' arg_list ')'
     {283, 0}, // 32: call_range ->  <empty>
     {283, 3}, // 33: call_range ('[') ->  '[' call_range_list ']'
     {285, 0}, // 34: call_range_list ->  <empty>
     {285, 1}, // 35: call_range_list ->  call_range_dim
     {285, 3}, // 36: call_range_list ('|') ->  call_range_list '|' call_range_dim
     {286, 2}, // 37: call_range_dim ('#') ->  '#' INT
     {286, 4}, // 38: call_range_dim ('#') ->  '#' INT ':' expr
     {286, 1}, // 39: call_range_dim ->  expr
     {284, 3}, // 40: arg_list (',') ->  arg_list ',' expr
     {284, 1}, // 41: arg_list ->  expr
     {284, 0}, // 42: arg_list ->  <empty>
     {279, 8}, // 43: for (FOR) ->  FOR EACH '(' for_spec_list ')' '{' for_body '}'
     {287, 3}, // 44: for_spec_list (';') ->  for_spec_list ';' for_spec
     {287, 2}, // 45: for_spec_list (';') ->  for_spec_list ';'
     {287, 1}, // 46: for_spec_list ->  for_spec
     {289, 5}, // 47: for_spec (IN) ->  for_iterator for_size for_hop IN for_domain
     {290, 0}, // 48: for_iterator ->  <empty>
     {290, 1}, // 49: for_iterator (ID) ->  ID
     {291, 0}, // 50: for_size ->  <empty>
     {291, 2}, // 51: for_size (TAKES) ->  TAKES int_or_id
     {292, 0}, // 52: for_hop ->  <empty>
     {292, 2}, // 53: for_hop (EVERY) ->  EVERY int_or_id
     {293, 1}, // 54: for_domain ->  range
     {293, 1}, // 55: for_domain ->  call
     {288, 0}, // 56: for_body ->  <empty>
     {288, 1}, // 57: for_body ->  expr
     {294, 1}, // 58: int_or_id (INT) ->  INT
     {294, 1}, // 59: int_or_id (ID) ->  ID
     {295, 1}, // 60: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_DEF}, {  5} },                 
    { {     271}, {  1} }, // program      
    { {     272}, {  2} }, // func_def_list
    { {     273}, {  3} }, // func_def     
    { {     260}, {  4} }, // ID           
    { {       0}, { -2} },                 
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  2} },       
    { {      59}, {  5} }, // ';'
    { {       0}, { -3} },       
};

SR__ s_4[] =
{
    { { REQ_DEF}, {  3} },                   
    { {     274}, {  6} }, // func_param_spec
    { {      40}, {  7} }, // '('            
    { {       0}, { -6} },                   
};

SR__ s_5[] =
{
    { { REQ_DEF}, {  4} },                 
    { {     272}, {  8} }, // func_def_list
    { {     273}, {  3} }, // func_def     
    { {     260}, {  4} }, // ID           
    { {       0}, { -2} },                 
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, { 2} },       
    { {        61}, { 9} }, // '='
    { {         0}, { 0} },       
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  3} },                   
    { {       276}, { 10} }, // func_param_list
    { {       260}, { 11} }, // ID             
    { {         0}, {  0} },                   
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, { 13} },             
    { {       275}, { 12} }, // func_body
    { {       277}, { 13} }, // expr     
    { {        40}, { 14} }, // '('      
    { {       278}, { 15} }, // range    
    { {       279}, { 16} }, // for      
    { {       280}, { 17} }, // call     
    { {       281}, { 18} }, // literal  
    { {       270}, { 19} }, // DOTDOT   
    { {       261}, { 20} }, // FOR      
    { {       260}, { 21} }, // ID       
    { {       258}, { 22} }, // INT      
    { {       259}, { 23} }, // REAL     
    { {         0}, {  0} },             
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 24} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_11[] =
{
    { { REQ_DEF}, {  2} },       
    { {      44}, { 25} }, // ','
    { {       0}, { -8} },       
};

SR__ s_12[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_13[] =
{
    { { REQ_DEF}, {  10} },          
    { {     266}, {  26} }, // EQ    
    { {     267}, {  27} }, // NEQ   
    { {     268}, {  28} }, // LESS  
    { {     269}, {  29} }, // MORE  
    { {      43}, {  30} }, // '+'   
    { {      45}, {  31} }, // '-'   
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -10} },          
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 35} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 36} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       262}, { 37} }, // EACH
    { {         0}, {  0} },        
};

SR__ s_21[] =
{
    { { REQ_DEF}, {   3} },             
    { {     282}, {  38} }, // call_args
    { {      40}, {  39} }, // '('      
    { {       0}, { -30} },             
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_24[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  3} },                   
    { {       276}, { 40} }, // func_param_list
    { {       260}, { 11} }, // ID             
    { {         0}, {  0} },                   
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 41} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 42} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 43} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 44} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 45} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 46} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 47} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 48} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_34[] =
{
    { { REQ_DEF}, {  11} },           
    { {     277}, {  49} }, // expr   
    { {      40}, {  14} }, // '('    
    { {     278}, {  15} }, // range  
    { {     279}, {  16} }, // for    
    { {     280}, {  17} }, // call   
    { {     281}, {  18} }, // literal
    { {     261}, {  20} }, // FOR    
    { {     260}, {  21} }, // ID     
    { {     258}, {  22} }, // INT    
    { {     259}, {  23} }, // REAL   
    { {       0}, { -27} },           
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 11} },          
    { {        41}, { 50} }, // ')'   
    { {       266}, { 26} }, // EQ    
    { {       267}, { 27} }, // NEQ   
    { {       268}, { 28} }, // LESS  
    { {       269}, { 29} }, // MORE  
    { {        43}, { 30} }, // '+'   
    { {        45}, { 31} }, // '-'   
    { {        42}, { 32} }, // '*'   
    { {        47}, { 33} }, // '/'   
    { {       270}, { 34} }, // DOTDOT
    { {         0}, {  0} },          
};

SR__ s_36[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 51} }, // '('
    { {         0}, {  0} },       
};

SR__ s_38[] =
{
    { { REQ_DEF}, {   3} },              
    { {     283}, {  52} }, // call_range
    { {      91}, {  53} }, // '['       
    { {       0}, { -32} },              
};

SR__ s_39[] =
{
    { { REQ_DEF}, {  13} },            
    { {     284}, {  54} }, // arg_list
    { {     277}, {  55} }, // expr    
    { {      40}, {  14} }, // '('     
    { {     278}, {  15} }, // range   
    { {     279}, {  16} }, // for     
    { {     280}, {  17} }, // call    
    { {     281}, {  18} }, // literal 
    { {     270}, {  19} }, // DOTDOT  
    { {     261}, {  20} }, // FOR     
    { {     260}, {  21} }, // ID      
    { {     258}, {  22} }, // INT     
    { {     259}, {  23} }, // REAL    
    { {       0}, { -42} },            
};

SR__ s_40[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_41[] =
{
    { { REQ_DEF}, {   6} },          
    { {      43}, {  30} }, // '+'   
    { {      45}, {  31} }, // '-'   
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -11} },          
};

SR__ s_42[] =
{
    { { REQ_DEF}, {   6} },          
    { {      43}, {  30} }, // '+'   
    { {      45}, {  31} }, // '-'   
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -12} },          
};

SR__ s_43[] =
{
    { { REQ_DEF}, {   6} },          
    { {      43}, {  30} }, // '+'   
    { {      45}, {  31} }, // '-'   
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -13} },          
};

SR__ s_44[] =
{
    { { REQ_DEF}, {   6} },          
    { {      43}, {  30} }, // '+'   
    { {      45}, {  31} }, // '-'   
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -14} },          
};

SR__ s_45[] =
{
    { { REQ_DEF}, {   4} },          
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -15} },          
};

SR__ s_46[] =
{
    { { REQ_DEF}, {   4} },          
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -16} },          
};

SR__ s_47[] =
{
    { { REQ_DEF}, {   2} },          
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -17} },          
};

SR__ s_48[] =
{
    { { REQ_DEF}, {   2} },          
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -18} },          
};

SR__ s_49[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_51[] =
{
    { { REQ_DEF}, {   5} },                 
    { {     287}, {  56} }, // for_spec_list
    { {     289}, {  57} }, // for_spec     
    { {     290}, {  58} }, // for_iterator 
    { {     260}, {  59} }, // ID           
    { {       0}, { -48} },                 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_53[] =
{
    { { REQ_DEF}, {  15} },                   
    { {     285}, {  60} }, // call_range_list
    { {     286}, {  61} }, // call_range_dim 
    { {      35}, {  62} }, // '#'            
    { {     277}, {  63} }, // expr           
    { {      40}, {  14} }, // '('            
    { {     278}, {  15} }, // range          
    { {     279}, {  16} }, // for            
    { {     280}, {  17} }, // call           
    { {     281}, {  18} }, // literal        
    { {     270}, {  19} }, // DOTDOT         
    { {     261}, {  20} }, // FOR            
    { {     260}, {  21} }, // ID             
    { {     258}, {  22} }, // INT            
    { {     259}, {  23} }, // REAL           
    { {       0}, { -34} },                   
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 64} }, // ')'
    { {        44}, { 65} }, // ','
    { {         0}, {  0} },       
};

SR__ s_55[] =
{
    { { REQ_DEF}, {  10} },          
    { {     266}, {  26} }, // EQ    
    { {     267}, {  27} }, // NEQ   
    { {     268}, {  28} }, // LESS  
    { {     269}, {  29} }, // MORE  
    { {      43}, {  30} }, // '+'   
    { {      45}, {  31} }, // '-'   
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -41} },          
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 66} }, // ')'
    { {        59}, { 67} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_58[] =
{
    { { REQ_DEF}, {   3} },            
    { {     291}, {  68} }, // for_size
    { {     263}, {  69} }, // TAKES   
    { {       0}, { -50} },            
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        93}, { 70} }, // ']'
    { {       124}, { 71} }, // '|'
    { {         0}, {  0} },       
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       258}, { 72} }, // INT
    { {         0}, {  0} },       
};

SR__ s_63[] =
{
    { { REQ_DEF}, {  10} },          
    { {     266}, {  26} }, // EQ    
    { {     267}, {  27} }, // NEQ   
    { {     268}, {  28} }, // LESS  
    { {     269}, {  29} }, // MORE  
    { {      43}, {  30} }, // '+'   
    { {      45}, {  31} }, // '-'   
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -39} },          
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 73} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 74} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   6} },                
    { {     289}, {  75} }, // for_spec    
    { {     290}, {  58} }, // for_iterator
    { {     260}, {  59} }, // ID          
    { {      59}, { -45} }, // ';'         
    { {      41}, { -45} }, // ')'         
    { {       0}, { -48} },                
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   3} },           
    { {     292}, {  76} }, // for_hop
    { {     264}, {  77} }, // EVERY  
    { {       0}, { -52} },           
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  4} },             
    { {       294}, { 78} }, // int_or_id
    { {       258}, { 79} }, // INT      
    { {       260}, { 80} }, // ID       
    { {         0}, {  0} },             
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, { 14} },                  
    { {       286}, { 81} }, // call_range_dim
    { {        35}, { 62} }, // '#'           
    { {       277}, { 63} }, // expr          
    { {        40}, { 14} }, // '('           
    { {       278}, { 15} }, // range         
    { {       279}, { 16} }, // for           
    { {       280}, { 17} }, // call          
    { {       281}, { 18} }, // literal       
    { {       270}, { 19} }, // DOTDOT        
    { {       261}, { 20} }, // FOR           
    { {       260}, { 21} }, // ID            
    { {       258}, { 22} }, // INT           
    { {       259}, { 23} }, // REAL          
    { {         0}, {  0} },                  
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   2} },       
    { {      58}, {  82} }, // ':'
    { {       0}, { -37} },       
};

SR__ s_73[] =
{
    { { REQ_DEF}, {  10} },          
    { {     266}, {  26} }, // EQ    
    { {     267}, {  27} }, // NEQ   
    { {     268}, {  28} }, // LESS  
    { {     269}, {  29} }, // MORE  
    { {      43}, {  30} }, // '+'   
    { {      45}, {  31} }, // '-'   
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -40} },          
};

SR__ s_74[] =
{
    { { REQ_DEF}, {  13} },            
    { {     288}, {  83} }, // for_body
    { {     277}, {  84} }, // expr    
    { {      40}, {  14} }, // '('     
    { {     278}, {  15} }, // range   
    { {     279}, {  16} }, // for     
    { {     280}, {  17} }, // call    
    { {     281}, {  18} }, // literal 
    { {     270}, {  19} }, // DOTDOT  
    { {     261}, {  20} }, // FOR     
    { {     260}, {  21} }, // ID      
    { {     258}, {  22} }, // INT     
    { {     259}, {  23} }, // REAL    
    { {       0}, { -56} },            
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       265}, { 85} }, // IN
    { {         0}, {  0} },      
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  4} },             
    { {       294}, { 86} }, // int_or_id
    { {       258}, { 79} }, // INT      
    { {       260}, { 80} }, // ID       
    { {         0}, {  0} },             
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       277}, { 87} }, // expr   
    { {        40}, { 14} }, // '('    
    { {       278}, { 15} }, // range  
    { {       279}, { 16} }, // for    
    { {       280}, { 17} }, // call   
    { {       281}, { 18} }, // literal
    { {       270}, { 19} }, // DOTDOT 
    { {       261}, { 20} }, // FOR    
    { {       260}, { 21} }, // ID     
    { {       258}, { 22} }, // INT    
    { {       259}, { 23} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       125}, { 88} }, // '}'
    { {         0}, {  0} },       
};

SR__ s_84[] =
{
    { { REQ_DEF}, {  10} },          
    { {     266}, {  26} }, // EQ    
    { {     267}, {  27} }, // NEQ   
    { {     268}, {  28} }, // LESS  
    { {     269}, {  29} }, // MORE  
    { {      43}, {  30} }, // '+'   
    { {      45}, {  31} }, // '-'   
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -57} },          
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, { 13} },              
    { {       293}, { 89} }, // for_domain
    { {       278}, { 90} }, // range     
    { {       280}, { 91} }, // call      
    { {       277}, { 92} }, // expr      
    { {       270}, { 19} }, // DOTDOT    
    { {       260}, { 21} }, // ID        
    { {        40}, { 14} }, // '('       
    { {       279}, { 16} }, // for       
    { {       281}, { 18} }, // literal   
    { {       261}, { 20} }, // FOR       
    { {       258}, { 22} }, // INT       
    { {       259}, { 23} }, // REAL      
    { {         0}, {  0} },              
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_87[] =
{
    { { REQ_DEF}, {  10} },          
    { {     266}, {  26} }, // EQ    
    { {     267}, {  27} }, // NEQ   
    { {     268}, {  28} }, // LESS  
    { {     269}, {  29} }, // MORE  
    { {      43}, {  30} }, // '+'   
    { {      45}, {  31} }, // '-'   
    { {      42}, {  32} }, // '*'   
    { {      47}, {  33} }, // '/'   
    { {     270}, {  34} }, // DOTDOT
    { {       0}, { -38} },          
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   3} },       
    { {      59}, { -54} }, // ';'
    { {      41}, { -54} }, // ')'
    { {       0}, { -20} },       
};

SR__ s_91[] =
{
    { { REQ_DEF}, {   3} },       
    { {      59}, { -55} }, // ';'
    { {      41}, { -55} }, // ')'
    { {       0}, { -22} },       
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, { 10} },          
    { {       270}, { 34} }, // DOTDOT
    { {       266}, { 26} }, // EQ    
    { {       267}, { 27} }, // NEQ   
    { {       268}, { 28} }, // LESS  
    { {       269}, { 29} }, // MORE  
    { {        43}, { 30} }, // '+'   
    { {        45}, { 31} }, // '-'   
    { {        42}, { 32} }, // '*'   
    { {        47}, { 33} }, // '/'   
    { {         0}, {  0} },          
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,
};

typedef std::unordered_map<int, char const *> SMap;
typedef SMap::value_type SMapVal;

SMapVal s_symArr[] =
{
    SMapVal(-2, "_UNDETERMINED_"),  // predefined symbols
    SMapVal(-1, "_EOF_"),
    SMapVal(256, "_error_"),

    SMapVal(257, "SCANNER_ERROR"),
    SMapVal(258, "INT"),
    SMapVal(259, "REAL"),
    SMapVal(260, "ID"),
    SMapVal(261, "FOR"),
    SMapVal(262, "EACH"),
    SMapVal(263, "TAKES"),
    SMapVal(264, "EVERY"),
    SMapVal(265, "IN"),
    SMapVal(266, "EQ"),
    SMapVal(267, "NEQ"),
    SMapVal(268, "LESS"),
    SMapVal(269, "MORE"),
    SMapVal(270, "DOTDOT"),
    SMapVal(271, "program"),
    SMapVal(272, "func_def_list"),
    SMapVal(273, "func_def"),
    SMapVal(274, "func_param_spec"),
    SMapVal(275, "func_body"),
    SMapVal(276, "func_param_list"),
    SMapVal(277, "expr"),
    SMapVal(278, "range"),
    SMapVal(279, "for"),
    SMapVal(280, "call"),
    SMapVal(281, "literal"),
    SMapVal(282, "call_args"),
    SMapVal(283, "call_range"),
    SMapVal(284, "arg_list"),
    SMapVal(285, "call_range_list"),
    SMapVal(286, "call_range_dim"),
    SMapVal(287, "for_spec_list"),
    SMapVal(288, "for_body"),
    SMapVal(289, "for_spec"),
    SMapVal(290, "for_iterator"),
    SMapVal(291, "for_size"),
    SMapVal(292, "for_hop"),
    SMapVal(293, "for_domain"),
    SMapVal(294, "int_or_id"),
    SMapVal(295, "program_$"),
};

SMap s_symbol
(
    s_symArr, s_symArr + sizeof(s_symArr) / sizeof(SMapVal)
);

} // anonymous namespace ends


// $insert namespace-open
namespace stream
{

// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}

// $insert debugfunctions
std::string ParserBase::symbol__(int value) const
{
    using namespace std;
    ostringstream ostr;
    SMap::const_iterator it = s_symbol.find(value);
    if (it != s_symbol.end())
        ostr << "`" << it->second << "'";
    else if (isprint(value))
        ostr << "`" << static_cast<char>(value) << "' (" << value << ")";
    else
        ostr << "'\\x" << setfill('0') << hex << setw(2) << value << "'";
    return ostr.str();
}


void Parser::print__()
{
// $insert print

    enum { _UNDETERMINED_ = -2 };

    std::cout << "Token: " << symbol__(d_token__) <<
                ", text: `";
        if (d_token__ == _UNDETERMINED_)
            std::cout << "'\n";
        else
            std::cout << d_scanner.matched() << "'\n";
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}


// $insert namespace-close
}


