// Generated by Bisonc++ V4.05.00 on Thu, 05 Jun 2014 11:59:52 -0700

// $insert class.ih
#include "parser_impl.hpp"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them

// $insert debugincludes
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <iomanip>

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {272, 1}, // 1: program ->  stmt_list
     {273, 1}, // 2: stmt_list ->  stmt
     {273, 3}, // 3: stmt_list (';') ->  stmt_list ';' stmt
     {274, 0}, // 4: stmt ->  <empty>
     {274, 1}, // 5: stmt ->  assignment
     {275, 6}, // 6: assignment (ID) ->  ID '(' param_list ')' '=' assignment_body
     {275, 3}, // 7: assignment (ID) ->  ID '=' assignment_body
     {276, 0}, // 8: param_list ->  <empty>
     {276, 1}, // 9: param_list (ID) ->  ID
     {276, 3}, // 10: param_list (',') ->  param_list ',' ID
     {277, 1}, // 11: assignment_body ->  complex_expr
     {277, 3}, // 12: assignment_body ('{') ->  '{' complex_expr '}'
     {277, 5}, // 13: assignment_body ('{') ->  '{' let_stmt_list ';' complex_expr '}'
     {279, 1}, // 14: let_stmt_list ->  let_stmt
     {279, 3}, // 15: let_stmt_list (';') ->  let_stmt_list ';' let_stmt
     {280, 0}, // 16: let_stmt ->  <empty>
     {280, 2}, // 17: let_stmt (LET) ->  LET stmt
     {280, 4}, // 18: let_stmt (LET) ->  LET '{' stmt_list '}'
     {281, 3}, // 19: expr (EQ) ->  expr EQ expr
     {281, 3}, // 20: expr (NEQ) ->  expr NEQ expr
     {281, 3}, // 21: expr (LESS) ->  expr LESS expr
     {281, 3}, // 22: expr (MORE) ->  expr MORE expr
     {281, 3}, // 23: expr ('+') ->  expr '+' expr
     {281, 3}, // 24: expr ('-') ->  expr '-' expr
     {281, 3}, // 25: expr ('*') ->  expr '*' expr
     {281, 3}, // 26: expr ('/') ->  expr '/' expr
     {281, 3}, // 27: expr ('(') ->  '(' expr ')'
     {281, 1}, // 28: expr ->  range
     {281, 1}, // 29: expr ->  call
     {281, 1}, // 30: expr ->  literal
     {285, 1}, // 31: simple_expr ->  expr
     {278, 1}, // 32: complex_expr ->  simple_expr
     {278, 1}, // 33: complex_expr ->  for
     {284, 1}, // 34: literal (INT) ->  INT
     {284, 1}, // 35: literal (REAL) ->  REAL
     {282, 3}, // 36: range (DOTDOT) ->  expr DOTDOT expr
     {282, 2}, // 37: range (DOTDOT) ->  expr DOTDOT
     {282, 2}, // 38: range (DOTDOT) ->  DOTDOT expr
     {283, 3}, // 39: call (ID) ->  ID call_args call_range
     {287, 0}, // 40: call_args ->  <empty>
     {287, 3}, // 41: call_args ('(') ->  '(' arg_list ')'
     {288, 0}, // 42: call_range ->  <empty>
     {288, 3}, // 43: call_range ('[') ->  '[' call_range_list ']'
     {290, 0}, // 44: call_range_list ->  <empty>
     {290, 1}, // 45: call_range_list ->  call_range_dim
     {290, 3}, // 46: call_range_list ('|') ->  call_range_list '|' call_range_dim
     {291, 2}, // 47: call_range_dim ('#') ->  '#' INT
     {291, 4}, // 48: call_range_dim ('#') ->  '#' INT ':' expr
     {291, 1}, // 49: call_range_dim ->  expr
     {289, 3}, // 50: arg_list (',') ->  arg_list ',' complex_expr
     {289, 1}, // 51: arg_list ->  complex_expr
     {289, 0}, // 52: arg_list ->  <empty>
     {286, 6}, // 53: for (FOR) ->  FOR EACH '(' for_spec_list ')' for_body
     {292, 3}, // 54: for_spec_list (';') ->  for_spec_list ';' for_spec
     {292, 2}, // 55: for_spec_list (';') ->  for_spec_list ';'
     {292, 1}, // 56: for_spec_list ->  for_spec
     {294, 5}, // 57: for_spec (IN) ->  for_iterator for_size for_hop IN for_domain
     {295, 0}, // 58: for_iterator ->  <empty>
     {295, 1}, // 59: for_iterator (ID) ->  ID
     {296, 0}, // 60: for_size ->  <empty>
     {296, 2}, // 61: for_size (TAKES) ->  TAKES int_or_id
     {297, 0}, // 62: for_hop ->  <empty>
     {297, 2}, // 63: for_hop (EVERY) ->  EVERY int_or_id
     {298, 1}, // 64: for_domain ->  range
     {298, 1}, // 65: for_domain ->  call
     {293, 0}, // 66: for_body ->  <empty>
     {293, 1}, // 67: for_body ->  assignment_body
     {299, 1}, // 68: int_or_id (INT) ->  INT
     {299, 1}, // 69: int_or_id (ID) ->  ID
     {300, 1}, // 70: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_DEF}, {  6} },              
    { {     272}, {  1} }, // program   
    { {     273}, {  2} }, // stmt_list 
    { {     274}, {  3} }, // stmt      
    { {     275}, {  4} }, // assignment
    { {     260}, {  5} }, // ID        
    { {       0}, { -4} },              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {  2} },       
    { {      59}, {  6} }, // ';'
    { {       0}, { -1} },       
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, { 3} },       
    { {        40}, { 7} }, // '('
    { {        61}, { 8} }, // '='
    { {         0}, { 0} },       
};

SR__ s_6[] =
{
    { { REQ_DEF}, {  4} },              
    { {     274}, {  9} }, // stmt      
    { {     275}, {  4} }, // assignment
    { {     260}, {  5} }, // ID        
    { {       0}, { -4} },              
};

SR__ s_7[] =
{
    { { REQ_DEF}, {  3} },              
    { {     276}, { 10} }, // param_list
    { {     260}, { 11} }, // ID        
    { {       0}, { -8} },              
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, { 16} },                   
    { {       277}, { 12} }, // assignment_body
    { {       278}, { 13} }, // complex_expr   
    { {       123}, { 14} }, // '{'            
    { {       285}, { 15} }, // simple_expr    
    { {       286}, { 16} }, // for            
    { {       281}, { 17} }, // expr           
    { {       262}, { 18} }, // FOR            
    { {        40}, { 19} }, // '('            
    { {       282}, { 20} }, // range          
    { {       283}, { 21} }, // call           
    { {       284}, { 22} }, // literal        
    { {       271}, { 23} }, // DOTDOT         
    { {       260}, { 24} }, // ID             
    { {       258}, { 25} }, // INT            
    { {       259}, { 26} }, // REAL           
    { {         0}, {  0} },                   
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 27} }, // ')'
    { {        44}, { 28} }, // ','
    { {         0}, {  0} },       
};

SR__ s_11[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_12[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_14[] =
{
    { { REQ_DEF}, {  17} },                 
    { {     278}, {  29} }, // complex_expr 
    { {     279}, {  30} }, // let_stmt_list
    { {     285}, {  15} }, // simple_expr  
    { {     286}, {  16} }, // for          
    { {     280}, {  31} }, // let_stmt     
    { {     281}, {  17} }, // expr         
    { {     262}, {  18} }, // FOR          
    { {     261}, {  32} }, // LET          
    { {      40}, {  19} }, // '('          
    { {     282}, {  20} }, // range        
    { {     283}, {  21} }, // call         
    { {     284}, {  22} }, // literal      
    { {     271}, {  23} }, // DOTDOT       
    { {     260}, {  24} }, // ID           
    { {     258}, {  25} }, // INT          
    { {     259}, {  26} }, // REAL         
    { {       0}, { -16} },                 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_17[] =
{
    { { REQ_DEF}, {  10} },          
    { {     267}, {  33} }, // EQ    
    { {     268}, {  34} }, // NEQ   
    { {     269}, {  35} }, // LESS  
    { {     270}, {  36} }, // MORE  
    { {      43}, {  37} }, // '+'   
    { {      45}, {  38} }, // '-'   
    { {      42}, {  39} }, // '*'   
    { {      47}, {  40} }, // '/'   
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -31} },          
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       263}, { 42} }, // EACH
    { {         0}, {  0} },        
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, { 10} },           
    { {       281}, { 43} }, // expr   
    { {        40}, { 19} }, // '('    
    { {       282}, { 20} }, // range  
    { {       283}, { 21} }, // call   
    { {       284}, { 22} }, // literal
    { {       271}, { 23} }, // DOTDOT 
    { {       260}, { 24} }, // ID     
    { {       258}, { 25} }, // INT    
    { {       259}, { 26} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, { 10} },           
    { {       281}, { 44} }, // expr   
    { {        40}, { 19} }, // '('    
    { {       282}, { 20} }, // range  
    { {       283}, { 21} }, // call   
    { {       284}, { 22} }, // literal
    { {       271}, { 23} }, // DOTDOT 
    { {       260}, { 24} }, // ID     
    { {       258}, { 25} }, // INT    
    { {       259}, { 26} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_24[] =
{
    { { REQ_DEF}, {   3} },             
    { {     287}, {  45} }, // call_args
    { {      40}, {  46} }, // '('      
    { {       0}, { -40} },             
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        61}, { 47} }, // '='
    { {         0}, {  0} },       
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       260}, { 48} }, // ID
    { {         0}, {  0} },      
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       125}, { 49} }, // '}'
    { {         0}, {  0} },       
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 50} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_32[] =
{
    { { REQ_DEF}, {  5} },              
    { {     274}, { 51} }, // stmt      
    { {     123}, { 52} }, // '{'       
    { {     275}, {  4} }, // assignment
    { {     260}, {  5} }, // ID        
    { {       0}, { -4} },              
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, { 10} },           
    { {       281}, { 53} }, // expr   
    { {        40}, { 19} }, // '('    
    { {       282}, { 20} }, // range  
    { {       283}, { 21} }, // call   
    { {       284}, { 22} }, // literal
    { {       271}, { 23} }, // DOTDOT 
    { {       260}, { 24} }, // ID     
    { {       258}, { 25} }, // INT    
    { {       259}, { 26} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 10} },           
    { {       281}, { 54} }, // expr   
    { {        40}, { 19} }, // '('    
    { {       282}, { 20} }, // range  
    { {       283}, { 21} }, // call   
    { {       284}, { 22} }, // literal
    { {       271}, { 23} }, // DOTDOT 
    { {       260}, { 24} }, // ID     
    { {       258}, { 25} }, // INT    
    { {       259}, { 26} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 10} },           
    { {       281}, { 55} }, // expr   
    { {        40}, { 19} }, // '('    
    { {       282}, { 20} }, // range  
    { {       283}, { 21} }, // call   
    { {       284}, { 22} }, // literal
    { {       271}, { 23} }, // DOTDOT 
    { {       260}, { 24} }, // ID     
    { {       258}, { 25} }, // INT    
    { {       259}, { 26} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, { 10} },           
    { {       281}, { 56} }, // expr   
    { {        40}, { 19} }, // '('    
    { {       282}, { 20} }, // range  
    { {       283}, { 21} }, // call   
    { {       284}, { 22} }, // literal
    { {       271}, { 23} }, // DOTDOT 
    { {       260}, { 24} }, // ID     
    { {       258}, { 25} }, // INT    
    { {       259}, { 26} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, { 10} },           
    { {       281}, { 57} }, // expr   
    { {        40}, { 19} }, // '('    
    { {       282}, { 20} }, // range  
    { {       283}, { 21} }, // call   
    { {       284}, { 22} }, // literal
    { {       271}, { 23} }, // DOTDOT 
    { {       260}, { 24} }, // ID     
    { {       258}, { 25} }, // INT    
    { {       259}, { 26} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, { 10} },           
    { {       281}, { 58} }, // expr   
    { {        40}, { 19} }, // '('    
    { {       282}, { 20} }, // range  
    { {       283}, { 21} }, // call   
    { {       284}, { 22} }, // literal
    { {       271}, { 23} }, // DOTDOT 
    { {       260}, { 24} }, // ID     
    { {       258}, { 25} }, // INT    
    { {       259}, { 26} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, { 10} },           
    { {       281}, { 59} }, // expr   
    { {        40}, { 19} }, // '('    
    { {       282}, { 20} }, // range  
    { {       283}, { 21} }, // call   
    { {       284}, { 22} }, // literal
    { {       271}, { 23} }, // DOTDOT 
    { {       260}, { 24} }, // ID     
    { {       258}, { 25} }, // INT    
    { {       259}, { 26} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, { 10} },           
    { {       281}, { 60} }, // expr   
    { {        40}, { 19} }, // '('    
    { {       282}, { 20} }, // range  
    { {       283}, { 21} }, // call   
    { {       284}, { 22} }, // literal
    { {       271}, { 23} }, // DOTDOT 
    { {       260}, { 24} }, // ID     
    { {       258}, { 25} }, // INT    
    { {       259}, { 26} }, // REAL   
    { {         0}, {  0} },           
};

SR__ s_41[] =
{
    { { REQ_DEF}, {   9} },           
    { {     281}, {  61} }, // expr   
    { {      40}, {  19} }, // '('    
    { {     282}, {  20} }, // range  
    { {     283}, {  21} }, // call   
    { {     284}, {  22} }, // literal
    { {     260}, {  24} }, // ID     
    { {     258}, {  25} }, // INT    
    { {     259}, {  26} }, // REAL   
    { {       0}, { -37} },           
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 62} }, // '('
    { {         0}, {  0} },       
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, { 11} },          
    { {        41}, { 63} }, // ')'   
    { {       267}, { 33} }, // EQ    
    { {       268}, { 34} }, // NEQ   
    { {       269}, { 35} }, // LESS  
    { {       270}, { 36} }, // MORE  
    { {        43}, { 37} }, // '+'   
    { {        45}, { 38} }, // '-'   
    { {        42}, { 39} }, // '*'   
    { {        47}, { 40} }, // '/'   
    { {       271}, { 41} }, // DOTDOT
    { {         0}, {  0} },          
};

SR__ s_44[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_45[] =
{
    { { REQ_DEF}, {   3} },              
    { {     288}, {  64} }, // call_range
    { {      91}, {  65} }, // '['       
    { {       0}, { -42} },              
};

SR__ s_46[] =
{
    { { REQ_DEF}, {  15} },                
    { {     289}, {  66} }, // arg_list    
    { {     278}, {  67} }, // complex_expr
    { {     285}, {  15} }, // simple_expr 
    { {     286}, {  16} }, // for         
    { {     281}, {  17} }, // expr        
    { {     262}, {  18} }, // FOR         
    { {      40}, {  19} }, // '('         
    { {     282}, {  20} }, // range       
    { {     283}, {  21} }, // call        
    { {     284}, {  22} }, // literal     
    { {     271}, {  23} }, // DOTDOT      
    { {     260}, {  24} }, // ID          
    { {     258}, {  25} }, // INT         
    { {     259}, {  26} }, // REAL        
    { {       0}, { -52} },                
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 16} },                   
    { {       277}, { 68} }, // assignment_body
    { {       278}, { 13} }, // complex_expr   
    { {       123}, { 14} }, // '{'            
    { {       285}, { 15} }, // simple_expr    
    { {       286}, { 16} }, // for            
    { {       281}, { 17} }, // expr           
    { {       262}, { 18} }, // FOR            
    { {        40}, { 19} }, // '('            
    { {       282}, { 20} }, // range          
    { {       283}, { 21} }, // call           
    { {       284}, { 22} }, // literal        
    { {       271}, { 23} }, // DOTDOT         
    { {       260}, { 24} }, // ID             
    { {       258}, { 25} }, // INT            
    { {       259}, { 26} }, // REAL           
    { {         0}, {  0} },                   
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_50[] =
{
    { { REQ_DEF}, {  16} },                
    { {     278}, {  69} }, // complex_expr
    { {     280}, {  70} }, // let_stmt    
    { {     285}, {  15} }, // simple_expr 
    { {     286}, {  16} }, // for         
    { {     261}, {  32} }, // LET         
    { {     281}, {  17} }, // expr        
    { {     262}, {  18} }, // FOR         
    { {      40}, {  19} }, // '('         
    { {     282}, {  20} }, // range       
    { {     283}, {  21} }, // call        
    { {     284}, {  22} }, // literal     
    { {     271}, {  23} }, // DOTDOT      
    { {     260}, {  24} }, // ID          
    { {     258}, {  25} }, // INT         
    { {     259}, {  26} }, // REAL        
    { {       0}, { -16} },                
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_52[] =
{
    { { REQ_DEF}, {  5} },              
    { {     273}, { 71} }, // stmt_list 
    { {     274}, {  3} }, // stmt      
    { {     275}, {  4} }, // assignment
    { {     260}, {  5} }, // ID        
    { {       0}, { -4} },              
};

SR__ s_53[] =
{
    { { REQ_DEF}, {   6} },          
    { {      43}, {  37} }, // '+'   
    { {      45}, {  38} }, // '-'   
    { {      42}, {  39} }, // '*'   
    { {      47}, {  40} }, // '/'   
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -19} },          
};

SR__ s_54[] =
{
    { { REQ_DEF}, {   6} },          
    { {      43}, {  37} }, // '+'   
    { {      45}, {  38} }, // '-'   
    { {      42}, {  39} }, // '*'   
    { {      47}, {  40} }, // '/'   
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -20} },          
};

SR__ s_55[] =
{
    { { REQ_DEF}, {   6} },          
    { {      43}, {  37} }, // '+'   
    { {      45}, {  38} }, // '-'   
    { {      42}, {  39} }, // '*'   
    { {      47}, {  40} }, // '/'   
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -21} },          
};

SR__ s_56[] =
{
    { { REQ_DEF}, {   6} },          
    { {      43}, {  37} }, // '+'   
    { {      45}, {  38} }, // '-'   
    { {      42}, {  39} }, // '*'   
    { {      47}, {  40} }, // '/'   
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -22} },          
};

SR__ s_57[] =
{
    { { REQ_DEF}, {   4} },          
    { {      42}, {  39} }, // '*'   
    { {      47}, {  40} }, // '/'   
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -23} },          
};

SR__ s_58[] =
{
    { { REQ_DEF}, {   4} },          
    { {      42}, {  39} }, // '*'   
    { {      47}, {  40} }, // '/'   
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -24} },          
};

SR__ s_59[] =
{
    { { REQ_DEF}, {   2} },          
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -25} },          
};

SR__ s_60[] =
{
    { { REQ_DEF}, {   2} },          
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -26} },          
};

SR__ s_61[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   5} },                 
    { {     292}, {  72} }, // for_spec_list
    { {     294}, {  73} }, // for_spec     
    { {     295}, {  74} }, // for_iterator 
    { {     260}, {  75} }, // ID           
    { {       0}, { -58} },                 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_65[] =
{
    { { REQ_DEF}, {  13} },                   
    { {     290}, {  76} }, // call_range_list
    { {     291}, {  77} }, // call_range_dim 
    { {      35}, {  78} }, // '#'            
    { {     281}, {  79} }, // expr           
    { {      40}, {  19} }, // '('            
    { {     282}, {  20} }, // range          
    { {     283}, {  21} }, // call           
    { {     284}, {  22} }, // literal        
    { {     271}, {  23} }, // DOTDOT         
    { {     260}, {  24} }, // ID             
    { {     258}, {  25} }, // INT            
    { {     259}, {  26} }, // REAL           
    { {       0}, { -44} },                   
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 80} }, // ')'
    { {        44}, { 81} }, // ','
    { {         0}, {  0} },       
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       125}, { 82} }, // '}'
    { {         0}, {  0} },       
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {       125}, { 83} }, // '}'
    { {        59}, {  6} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 84} }, // ')'
    { {        59}, { 85} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   3} },            
    { {     296}, {  86} }, // for_size
    { {     264}, {  87} }, // TAKES   
    { {       0}, { -60} },            
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        93}, { 88} }, // ']'
    { {       124}, { 89} }, // '|'
    { {         0}, {  0} },       
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       258}, { 90} }, // INT
    { {         0}, {  0} },       
};

SR__ s_79[] =
{
    { { REQ_DEF}, {  10} },          
    { {     267}, {  33} }, // EQ    
    { {     268}, {  34} }, // NEQ   
    { {     269}, {  35} }, // LESS  
    { {     270}, {  36} }, // MORE  
    { {      43}, {  37} }, // '+'   
    { {      45}, {  38} }, // '-'   
    { {      42}, {  39} }, // '*'   
    { {      47}, {  40} }, // '/'   
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -49} },          
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, { 14} },                
    { {       278}, { 91} }, // complex_expr
    { {       285}, { 15} }, // simple_expr 
    { {       286}, { 16} }, // for         
    { {       281}, { 17} }, // expr        
    { {       262}, { 18} }, // FOR         
    { {        40}, { 19} }, // '('         
    { {       282}, { 20} }, // range       
    { {       283}, { 21} }, // call        
    { {       284}, { 22} }, // literal     
    { {       271}, { 23} }, // DOTDOT      
    { {       260}, { 24} }, // ID          
    { {       258}, { 25} }, // INT         
    { {       259}, { 26} }, // REAL        
    { {         0}, {  0} },                
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_84[] =
{
    { { REQ_DEF}, {  17} },                   
    { {     293}, {  92} }, // for_body       
    { {     277}, {  93} }, // assignment_body
    { {     278}, {  13} }, // complex_expr   
    { {     123}, {  14} }, // '{'            
    { {     285}, {  15} }, // simple_expr    
    { {     286}, {  16} }, // for            
    { {     281}, {  17} }, // expr           
    { {     262}, {  18} }, // FOR            
    { {      40}, {  19} }, // '('            
    { {     282}, {  20} }, // range          
    { {     283}, {  21} }, // call           
    { {     284}, {  22} }, // literal        
    { {     271}, {  23} }, // DOTDOT         
    { {     260}, {  24} }, // ID             
    { {     258}, {  25} }, // INT            
    { {     259}, {  26} }, // REAL           
    { {       0}, { -66} },                   
};

SR__ s_85[] =
{
    { { REQ_DEF}, {   6} },                
    { {     294}, {  94} }, // for_spec    
    { {     295}, {  74} }, // for_iterator
    { {     260}, {  75} }, // ID          
    { {      59}, { -55} }, // ';'         
    { {      41}, { -55} }, // ')'         
    { {       0}, { -58} },                
};

SR__ s_86[] =
{
    { { REQ_DEF}, {   3} },           
    { {     297}, {  95} }, // for_hop
    { {     265}, {  96} }, // EVERY  
    { {       0}, { -62} },           
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  4} },             
    { {       299}, { 97} }, // int_or_id
    { {       258}, { 98} }, // INT      
    { {       260}, { 99} }, // ID       
    { {         0}, {  0} },             
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  12} },                  
    { {       291}, { 100} }, // call_range_dim
    { {        35}, {  78} }, // '#'           
    { {       281}, {  79} }, // expr          
    { {        40}, {  19} }, // '('           
    { {       282}, {  20} }, // range         
    { {       283}, {  21} }, // call          
    { {       284}, {  22} }, // literal       
    { {       271}, {  23} }, // DOTDOT        
    { {       260}, {  24} }, // ID            
    { {       258}, {  25} }, // INT           
    { {       259}, {  26} }, // REAL          
    { {         0}, {   0} },                  
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   2} },       
    { {      58}, { 101} }, // ':'
    { {       0}, { -47} },       
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   2} },      
    { {       266}, { 102} }, // IN
    { {         0}, {   0} },      
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {   4} },             
    { {       299}, { 103} }, // int_or_id
    { {       258}, {  98} }, // INT      
    { {       260}, {  99} }, // ID       
    { {         0}, {   0} },             
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {  10} },           
    { {       281}, { 104} }, // expr   
    { {        40}, {  19} }, // '('    
    { {       282}, {  20} }, // range  
    { {       283}, {  21} }, // call   
    { {       284}, {  22} }, // literal
    { {       271}, {  23} }, // DOTDOT 
    { {       260}, {  24} }, // ID     
    { {       258}, {  25} }, // INT    
    { {       259}, {  26} }, // REAL   
    { {         0}, {   0} },           
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {  11} },              
    { {       298}, { 105} }, // for_domain
    { {       282}, { 106} }, // range     
    { {       283}, { 107} }, // call      
    { {       281}, { 108} }, // expr      
    { {       271}, {  23} }, // DOTDOT    
    { {       260}, {  24} }, // ID        
    { {        40}, {  19} }, // '('       
    { {       284}, {  22} }, // literal   
    { {       258}, {  25} }, // INT       
    { {       259}, {  26} }, // REAL      
    { {         0}, {   0} },              
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_104[] =
{
    { { REQ_DEF}, {  10} },          
    { {     267}, {  33} }, // EQ    
    { {     268}, {  34} }, // NEQ   
    { {     269}, {  35} }, // LESS  
    { {     270}, {  36} }, // MORE  
    { {      43}, {  37} }, // '+'   
    { {      45}, {  38} }, // '-'   
    { {      42}, {  39} }, // '*'   
    { {      47}, {  40} }, // '/'   
    { {     271}, {  41} }, // DOTDOT
    { {       0}, { -48} },          
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_106[] =
{
    { { REQ_DEF}, {   3} },       
    { {      59}, { -64} }, // ';'
    { {      41}, { -64} }, // ')'
    { {       0}, { -28} },       
};

SR__ s_107[] =
{
    { { REQ_DEF}, {   3} },       
    { {      59}, { -65} }, // ';'
    { {      41}, { -65} }, // ')'
    { {       0}, { -29} },       
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, { 10} },          
    { {       271}, { 41} }, // DOTDOT
    { {       267}, { 33} }, // EQ    
    { {       268}, { 34} }, // NEQ   
    { {       269}, { 35} }, // LESS  
    { {       270}, { 36} }, // MORE  
    { {        43}, { 37} }, // '+'   
    { {        45}, { 38} }, // '-'   
    { {        42}, { 39} }, // '*'   
    { {        47}, { 40} }, // '/'   
    { {         0}, {  0} },          
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,
};

typedef std::unordered_map<int, char const *> SMap;
typedef SMap::value_type SMapVal;

SMapVal s_symArr[] =
{
    SMapVal(-2, "_UNDETERMINED_"),  // predefined symbols
    SMapVal(-1, "_EOF_"),
    SMapVal(256, "_error_"),

    SMapVal(257, "SCANNER_ERROR"),
    SMapVal(258, "INT"),
    SMapVal(259, "REAL"),
    SMapVal(260, "ID"),
    SMapVal(261, "LET"),
    SMapVal(262, "FOR"),
    SMapVal(263, "EACH"),
    SMapVal(264, "TAKES"),
    SMapVal(265, "EVERY"),
    SMapVal(266, "IN"),
    SMapVal(267, "EQ"),
    SMapVal(268, "NEQ"),
    SMapVal(269, "LESS"),
    SMapVal(270, "MORE"),
    SMapVal(271, "DOTDOT"),
    SMapVal(272, "program"),
    SMapVal(273, "stmt_list"),
    SMapVal(274, "stmt"),
    SMapVal(275, "assignment"),
    SMapVal(276, "param_list"),
    SMapVal(277, "assignment_body"),
    SMapVal(278, "complex_expr"),
    SMapVal(279, "let_stmt_list"),
    SMapVal(280, "let_stmt"),
    SMapVal(281, "expr"),
    SMapVal(282, "range"),
    SMapVal(283, "call"),
    SMapVal(284, "literal"),
    SMapVal(285, "simple_expr"),
    SMapVal(286, "for"),
    SMapVal(287, "call_args"),
    SMapVal(288, "call_range"),
    SMapVal(289, "arg_list"),
    SMapVal(290, "call_range_list"),
    SMapVal(291, "call_range_dim"),
    SMapVal(292, "for_spec_list"),
    SMapVal(293, "for_body"),
    SMapVal(294, "for_spec"),
    SMapVal(295, "for_iterator"),
    SMapVal(296, "for_size"),
    SMapVal(297, "for_hop"),
    SMapVal(298, "for_domain"),
    SMapVal(299, "int_or_id"),
    SMapVal(300, "program_$"),
};

SMap s_symbol
(
    s_symArr, s_symArr + sizeof(s_symArr) / sizeof(SMapVal)
);

} // anonymous namespace ends


// $insert namespace-open
namespace stream
{

// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}

// $insert debugfunctions
std::string ParserBase::symbol__(int value) const
{
    using namespace std;
    ostringstream ostr;
    SMap::const_iterator it = s_symbol.find(value);
    if (it != s_symbol.end())
        ostr << "`" << it->second << "'";
    else if (isprint(value))
        ostr << "`" << static_cast<char>(value) << "' (" << value << ")";
    else
        ostr << "'\\x" << setfill('0') << hex << setw(2) << value << "'";
    return ostr.str();
}


void Parser::print__()
{
// $insert print

    enum { _UNDETERMINED_ = -2 };

    std::cout << "Token: " << symbol__(d_token__) <<
                ", text: `";
        if (d_token__ == _UNDETERMINED_)
            std::cout << "'\n";
        else
            std::cout << d_scanner.matched() << "'\n";
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}


// $insert namespace-close
}


