// Generated by Flexc++ V1.08.00 on Sun, 25 May 2014 14:03:00 -0700

// $insert class_h
#include "scanner.h"

// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace stream without prefixing stream::
//using namespace stream;
