name: Test on Mac

on: [push]

jobs:
  test:

    runs-on: macOS-latest

    steps:

    - run: |
        wget https://github.com/jleben/arrp/releases/download/test-release/arrp_1.0.0_macos.zip
        unzip arrp_1.0.0_macos.zip
        cd arrp_1.0.0_macos
        echo "main = 1;" > test.arrp
        ARRP_HOME=. && ./bin/arrp test.arrp --exec test
        ./test
