name: Test on Mac

on: [push]

jobs:
  test:

    runs-on: macOS-latest

    steps:

    - run: |
        wget https://github.com/jleben/arrp/releases/download/test-release/arrp_1.0.0_macos.zip
        unzip arrp_1.0.0_macos.zip
        cd arrp_1.0.0_macos
        echo "input x : [~]int; output y = 2*x;" > test.arrp
        ARRP_HOME=. ./bin/arrp test.arrp --exe test
        echo 1 3 5 | ./test > output.txt
        echo -en "2\n6\n10\n" > expected.txt
        diff output.txt expected.txt
